<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="SAVITAP" ignored="0" name="ErrorValidation" tests="3" failures="2" timestamp="2024-08-16T17:02:46 IST" time="19.14" errors="0">
  <testcase name="LoginCheck" time="0.605" classname="seleniumframework.ErrorValidationTest">
    <failure type="java.lang.AssertionError" message="expected [Login Successfully] but found [Login Successfully........]">
      <![CDATA[java.lang.AssertionError: expected [Login Successfully] but found [Login Successfully........]
at seleniumframework.ErrorValidationTest.LoginCheck(ErrorValidationTest.java:17)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- LoginCheck -->
  <testcase name="checkProductinCart" time="0.895" classname="seleniumframework.ErrorValidationTest">
    <skipped/>
  </testcase> <!-- checkProductinCart -->
  <testcase name="checkProductinCart" time="0.864" classname="seleniumframework.ErrorValidationTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at seleniumframework.pageobjects.CataloguePage.addtoCart(CataloguePage.java:49)
at seleniumframework.ErrorValidationTest.checkProductinCart(ErrorValidationTest.java:26)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- checkProductinCart -->
</testsuite> <!-- ErrorValidation -->
